apiVersion: v1
kind: Service
metadata:
  namespace: account-service
  labels:
    app: account-service
  name: account-service
spec:
  ports:
  
    - protocol: TCP
      port: 4300
      targetPort: 4300
   
   
  selector:
    app: account-service
  type: ClusterIP
